name: CI

on:
  push:
    branches: [ Lab9 ]
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo "Hello, GitHub Actions!"
